/* =====================================================================
 *  محتوى المعرض  |  Portfolio content
 *  ---------------------------------------------------------------------
 *  كل النصوص هنا بيانات فقط: عدّلها كما تشاء بدون لمس أي كود آخر.
 *  Everything the visitor reads lives in this file. Edit freely.
 *
 *  HOW TO EDIT
 *   1. Change `profile` (name, role, city, email…) in BOTH languages.
 *   2. Replace the placeholder projects / skills / roles with your own.
 *   3. Keep the zone ids: about, projects, skills, experience, contact.
 *   4. `level` for skills is 0-100. `link` '#' means "no link yet".
 *   5. Add another language by copying the `en` block under a new key
 *      (and adding it to the language switcher in ui.js `LANGS`).
 * ===================================================================== */

export const ZONE_IDS = ['about', 'projects', 'skills', 'experience', 'contact'];

export const content = {
  /* ------------------------------------------------------------------ */
  /*  العربية (الافتراضية)                                              */
  /* ------------------------------------------------------------------ */
  ar: {
    lang: 'ar',
    dir: 'rtl',
    langName: 'العربية',
    profile: {
      name: 'اسمك هنا',
      role: 'مطوّر ومصمّم تجارب تفاعلية',
      location: 'الرياض، المملكة العربية السعودية',
      email: 'hello@example.com',
      initials: 'اس',
    },
    ui: {
      title: 'رحلة الصحراء',
      subtitle: 'معرض أعمال تفاعلي على ظهر جمل',
      byline: 'بقلم اسمك هنا',
      start: 'ابدأ الرحلة',
      loading: 'جارٍ تجهيز القافلة…',
      ready: 'القافلة جاهزة',
      loadingTips: [
        'اقترب من الأعمدة المتوهّجة لتفتح محطات المعرض.',
        'الجمل يتعب إن أسرع طويلًا، فامنحه وقتًا ليستعيد أنفاسه.',
        'اضغط زر النداء لتسمع رغاء جملك.',
        'اتبع السهم الذهبي ليدلّك على أقرب محطة لم تزرها.',
        'الكثبان أجمل عند الغروب، جرّب تبديل النهار والليل.',
        'ثمة أشياء كثيرة في الصحراء تستحق أن تصطدم بها بلطف.',
      ],
      controlsTitle: 'طريقة التحكم',
      controlsKeyboard: [
        { keys: ['W', 'A', 'S', 'D'], alt: ['↑', '←', '↓', '→'], label: 'قيادة الجمل' },
        { keys: ['Shift'], label: 'عَدْو سريع' },
        { keys: ['Space'], label: 'فرملة' },
        { keys: ['H'], label: 'نداء الجمل' },
        { keys: ['R'], label: 'إعادة الموضع' },
        { keys: ['Enter'], label: 'دخول المحطة' },
      ],
      controlsTouch: [
        { icon: 'joystick', label: 'اسحب بإبهامك الأيسر للتوجيه' },
        { icon: 'sprint', label: 'اضغط باستمرار على «عدو» للتسارع' },
        { icon: 'call', label: 'اضغط «نداء» ليرغو الجمل' },
        { icon: 'brake', label: 'اضغط باستمرار على «فرملة» للتوقّف' },
      ],
      controlsGamepad: 'ذراع التحكم: العصا اليسرى للقيادة، A للعدو، B للفرملة، X للنداء',
      rotateHint: 'للحصول على أفضل تجربة أدِر هاتفك أفقيًا',
      enterPrompt: 'اضغط للدخول',
      enterPromptKey: 'اضغط Enter أو المس للدخول',
      close: 'إغلاق',
      back: 'رجوع',
      settings: 'الإعدادات',
      help: 'المساعدة',
      hud: {
        stamina: 'الطاقة',
        zones: 'المحطات',
        nearest: 'أقرب محطة',
        meters: 'م',
        allVisited: 'زرت كل المحطات',
        minimap: 'الخريطة',
        visited: 'تمت زيارتها',
      },
      celebrate: 'أتممت الرحلة! شكرًا لزيارتك كل المحطات',
      zoneOpened: (t) => `فُتحت محطة ${t}`,
      zoneClosed: 'عدت إلى الصحراء',
      toastStamina: 'جملك متعب، دعه يستريح قليلًا',
      toastWelcome: 'أهلًا بك! ابدأ بالتوجّه نحو السهم الذهبي',
      settingsPanel: {
        sound: 'المؤثرات الصوتية',
        music: 'الموسيقى',
        language: 'اللغة',
        quality: 'جودة الرسوم',
        qualityAuto: 'تلقائي',
        qualityLow: 'منخفضة',
        qualityMed: 'متوسطة',
        qualityHigh: 'عالية',
        time: 'وقت اليوم',
        day: 'نهار',
        night: 'ليل',
        on: 'يعمل',
        off: 'متوقف',
        fullscreen: 'ملء الشاشة',
        helpTitle: 'مفاتيح التحكم',
      },
      touch: { sprint: 'عدو', call: 'نداء', brake: 'فرملة' },
      copy: 'نسخ',
      copied: 'تم نسخ البريد',
      openLink: 'عرض المشروع',
      year: 'السنة',
      skipToContent: 'تخطَّ إلى المحتوى',
      unsupported: 'متصفحك لا يدعم WebGL. جرّب متصفحًا أحدث.',
    },
    zones: {
      about: {
        title: 'من أنا',
        kicker: 'المحطة الأولى',
        blurb: 'نبذة عني وعن شغفي',
        icon: 'user',
        color: '#e0a458',
        bio: [
          'أنا مطوّر ومصمّم تجارب تفاعلية أصنع مواقع وألعابًا صغيرة تجمع بين الهندسة والحكاية. أحب أن أحوّل الفكرة العابرة إلى شيء يُلمس ويُلعب به على الشاشة.',
          'بدأت رحلتي مع الويب منذ أكثر من عشر سنوات، وما زلت أدهش كل مرة يعمل فيها ما كتبته للمرة الأولى. أؤمن بأن الواجهة الجيدة تُشبه الواحة: تدخلها متعبًا فتخرج منها منتعشًا.',
          'أعمل الآن مع فرق صغيرة وشركات ناشئة، وأشارك ما أتعلمه عبر الكتابة والمحاضرات والمصادر المفتوحة.',
        ],
        factsTitle: 'حقائق سريعة',
        facts: [
          { icon: 'coffee', text: 'أشرب القهوة العربية بالهيل، ثلاثة فناجين على الأقل' },
          { icon: 'star', text: 'أصوّر النجوم في ليالي الصحراء في عطلات نهاية الأسبوع' },
          { icon: 'note', text: 'أعزف العود بشكل متوسط، وأبرمج بشكل أفضل' },
          { icon: 'compass', text: 'زرت أحد عشر بلدًا وأبحث عن الثاني عشر' },
        ],
      },
      projects: {
        title: 'المشاريع',
        kicker: 'المحطة الثانية',
        blurb: 'ستة أعمال أفتخر بها',
        icon: 'grid',
        color: '#c8553d',
        items: [
          {
            title: 'نجمة سُهيل',
            year: '٢٠٢٦',
            desc: 'تجربة ثلاثية الأبعاد لرصد النجوم كما كان يراها الملّاحون العرب، مع خرائط للأنواء والمنازل القمرية.',
            tags: ['Three.js', 'WebGL', 'GLSL'],
            link: '#',
            hue: 215,
          },
          {
            title: 'سوق الكلمات',
            year: '٢٠٢٥',
            desc: 'منصة ألعاب لتعلّم المفردات العربية للأطفال، تُكافئ الفضول بدل الحفظ وتتكيّف مع مستوى كل طفل.',
            tags: ['React', 'Node.js', 'PostgreSQL'],
            link: '#',
            hue: 24,
          },
          {
            title: 'قافلة',
            year: '٢٠٢٥',
            desc: 'لوحة تحكم لتتبّع الشحنات لحظة بلحظة على الخريطة، مع تنبيهات ذكية عند التأخّر أو تغيّر المسار.',
            tags: ['TypeScript', 'WebSockets', 'Mapbox'],
            link: '#',
            hue: 168,
          },
          {
            title: 'خطّاط',
            year: '٢٠٢٤',
            desc: 'أداة رسم تحاكي قلم القصب وتقترح الحروف المتصلة أثناء الكتابة بالخطوط العربية التقليدية.',
            tags: ['Canvas', 'Python', 'ML'],
            link: '#',
            hue: 340,
          },
          {
            title: 'واحة',
            year: '٢٠٢٤',
            desc: 'تطبيق جوّال هادئ يذكّرك بشرب الماء ويحوّل عاداتك اليومية إلى واحة صغيرة تنمو أمامك.',
            tags: ['Flutter', 'Firebase', 'Lottie'],
            link: '#',
            hue: 130,
          },
          {
            title: 'مقام',
            year: '٢٠٢٣',
            desc: 'مشغّل موسيقى توليدية يؤلّف ألحانًا على مقامات الحجاز والنهاوند والصبا مباشرة داخل المتصفح.',
            tags: ['WebAudio', 'Svelte', 'MIDI'],
            link: '#',
            hue: 275,
          },
        ],
      },
      skills: {
        title: 'المهارات',
        kicker: 'المحطة الثالثة',
        blurb: 'الأدوات التي أجيدها',
        icon: 'bolt',
        color: '#2a9d8f',
        groups: [
          {
            title: 'الواجهات الأمامية',
            items: [
              { name: 'JavaScript', level: 95 },
              { name: 'TypeScript', level: 88 },
              { name: 'CSS و SVG', level: 92 },
              { name: 'React', level: 85 },
            ],
          },
          {
            title: 'الرسوم ثلاثية الأبعاد',
            items: [
              { name: 'Three.js', level: 90 },
              { name: 'GLSL والمظلّلات', level: 78 },
              { name: 'Blender', level: 70 },
              { name: 'WebAudio', level: 75 },
            ],
          },
          {
            title: 'الخلفية والأدوات',
            items: [
              { name: 'Node.js', level: 82 },
              { name: 'Python', level: 68 },
              { name: 'Git', level: 90 },
              { name: 'Figma', level: 80 },
            ],
          },
        ],
        levelWord: (v) => (v >= 90 ? 'خبير' : v >= 80 ? 'متقدّم' : v >= 65 ? 'متوسط' : 'مبتدئ'),
      },
      experience: {
        title: 'الخبرات',
        kicker: 'المحطة الرابعة',
        blurb: 'أين عملت وماذا تعلّمت',
        icon: 'path',
        color: '#5c6bc0',
        roles: [
          {
            role: 'مطوّر تجارب تفاعلية أول',
            company: 'استوديو الكثبان',
            period: '٢٠٢٣ — الآن',
            desc: 'أقود فريقًا صغيرًا يصمّم مواقع وتجارب ثلاثية الأبعاد لعلامات تجارية إقليمية، وأضع معايير الأداء والوصولية.',
          },
          {
            role: 'مطوّر واجهات أمامية',
            company: 'شركة نبراس للتقنية',
            period: '٢٠٢٠ — ٢٠٢٣',
            desc: 'بنيت نظام تصميم عربي أولًا يدعم الاتجاهين، وخفّضت زمن تحميل التطبيق الرئيسي إلى النصف.',
          },
          {
            role: 'مطوّر مستقل',
            company: 'أعمال حرّة',
            period: '٢٠١٨ — ٢٠٢٠',
            desc: 'أنجزت أكثر من عشرين مشروعًا لمتاجر ومبادرات ثقافية ومؤسسات ناشئة في الخليج والمشرق.',
          },
          {
            role: 'متدرّب برمجة',
            company: 'مختبر الابتكار الجامعي',
            period: '٢٠١٦ — ٢٠١٨',
            desc: 'أول لقاء جدّي مع الويب والرسوم؛ صنعت فيه لعبتي الأولى ونسيت النوم لأسابيع.',
          },
        ],
      },
      contact: {
        title: 'تواصل معي',
        kicker: 'المحطة الأخيرة',
        blurb: 'يسعدني سماع فكرتك',
        icon: 'mail',
        color: '#e76f51',
        message:
          'عندك فكرة أو مشروع أو مجرد سؤال؟ راسلني وسأردّ خلال يومين. أحب المشاريع التي تحمل حكاية، وأفتح الباب دائمًا للتعاون.',
        emailLabel: 'البريد الإلكتروني',
        socialsTitle: 'حساباتي',
        availability: 'متاح لمشاريع جديدة ابتداءً من الشهر القادم',
        socials: [
          { name: 'GitHub', handle: '@yourname', url: '#' },
          { name: 'LinkedIn', handle: 'in/yourname', url: '#' },
          { name: 'X', handle: '@yourname', url: '#' },
          { name: 'Instagram', handle: '@yourname', url: '#' },
        ],
      },
    },
  },

  /* ------------------------------------------------------------------ */
  /*  English                                                           */
  /* ------------------------------------------------------------------ */
  en: {
    lang: 'en',
    dir: 'ltr',
    langName: 'English',
    profile: {
      name: 'Your Name',
      role: 'Interactive developer & designer',
      location: 'Riyadh, Saudi Arabia',
      email: 'hello@example.com',
      initials: 'YN',
    },
    ui: {
      title: 'Desert Journey',
      subtitle: 'An interactive portfolio on camelback',
      byline: 'by Your Name',
      start: 'Start the journey',
      loading: 'Loading the caravan…',
      ready: 'Caravan ready',
      loadingTips: [
        'Ride into the glowing pillars to open the portfolio stops.',
        'Your camel tires if it sprints for long, so let it catch its breath.',
        'Press the call button to hear your camel groan.',
        'Follow the golden arrow to the nearest stop you have not visited.',
        'Dunes look best at dusk, so try switching between day and night.',
        'The desert has plenty of things worth bumping into, gently.',
      ],
      controlsTitle: 'Controls',
      controlsKeyboard: [
        { keys: ['W', 'A', 'S', 'D'], alt: ['↑', '←', '↓', '→'], label: 'Steer the camel' },
        { keys: ['Shift'], label: 'Gallop' },
        { keys: ['Space'], label: 'Brake' },
        { keys: ['H'], label: 'Call out' },
        { keys: ['R'], label: 'Reset position' },
        { keys: ['Enter'], label: 'Enter a stop' },
      ],
      controlsTouch: [
        { icon: 'joystick', label: 'Drag with your left thumb to steer' },
        { icon: 'sprint', label: 'Hold SPRINT to gallop' },
        { icon: 'call', label: 'Tap CALL to make the camel groan' },
        { icon: 'brake', label: 'Hold BRAKE to stop' },
      ],
      controlsGamepad: 'Gamepad: left stick to steer, A to sprint, B to brake, X to call',
      rotateHint: 'For the best experience, rotate your phone to landscape',
      enterPrompt: 'Tap to enter',
      enterPromptKey: 'Press Enter or tap to enter',
      close: 'Close',
      back: 'Back',
      settings: 'Settings',
      help: 'Help',
      hud: {
        stamina: 'Stamina',
        zones: 'Stops',
        nearest: 'Nearest stop',
        meters: 'm',
        allVisited: 'All stops visited',
        minimap: 'Map',
        visited: 'Visited',
      },
      celebrate: 'Journey complete! Thank you for visiting every stop',
      zoneOpened: (t) => `${t} opened`,
      zoneClosed: 'Back in the desert',
      toastStamina: 'Your camel is tired, let it rest a moment',
      toastWelcome: 'Welcome! Head toward the golden arrow to begin',
      settingsPanel: {
        sound: 'Sound effects',
        music: 'Music',
        language: 'Language',
        quality: 'Graphics quality',
        qualityAuto: 'Auto',
        qualityLow: 'Low',
        qualityMed: 'Medium',
        qualityHigh: 'High',
        time: 'Time of day',
        day: 'Day',
        night: 'Night',
        on: 'On',
        off: 'Off',
        fullscreen: 'Fullscreen',
        helpTitle: 'Controls',
      },
      touch: { sprint: 'SPRINT', call: 'CALL', brake: 'BRAKE' },
      copy: 'Copy',
      copied: 'Email copied',
      openLink: 'View project',
      year: 'Year',
      skipToContent: 'Skip to content',
      unsupported: 'Your browser does not support WebGL. Please try a newer one.',
    },
    zones: {
      about: {
        title: 'About me',
        kicker: 'Stop one',
        blurb: 'A little about me and what drives me',
        icon: 'user',
        color: '#e0a458',
        bio: [
          'I am a developer and designer who builds interactive sites and small games where engineering meets storytelling. I love turning a passing idea into something you can touch and play with on screen.',
          'I started on the web more than ten years ago and I am still amazed every time something I wrote runs for the first time. I believe a good interface is like an oasis: you enter tired and leave refreshed.',
          'Today I work with small teams and start-ups, and share what I learn through writing, talks and open source.',
        ],
        factsTitle: 'Quick facts',
        facts: [
          { icon: 'coffee', text: 'Cardamom coffee, three cups minimum' },
          { icon: 'star', text: 'Photographs stars in the desert on weekends' },
          { icon: 'note', text: 'Plays the oud averagely, codes better' },
          { icon: 'compass', text: 'Visited eleven countries, hunting for the twelfth' },
        ],
      },
      projects: {
        title: 'Projects',
        kicker: 'Stop two',
        blurb: 'Six pieces of work I am proud of',
        icon: 'grid',
        color: '#c8553d',
        items: [
          {
            title: 'Suhail Star',
            year: '2026',
            desc: 'A 3D stargazing experience showing the sky as Arab navigators saw it, with maps of the seasonal stars and lunar mansions.',
            tags: ['Three.js', 'WebGL', 'GLSL'],
            link: '#',
            hue: 215,
          },
          {
            title: 'Word Souk',
            year: '2025',
            desc: 'A game platform for children learning Arabic vocabulary. It rewards curiosity over memorising and adapts to each child.',
            tags: ['React', 'Node.js', 'PostgreSQL'],
            link: '#',
            hue: 24,
          },
          {
            title: 'Caravan',
            year: '2025',
            desc: 'A real-time shipment tracking dashboard on a live map, with smart alerts when a delivery is late or rerouted.',
            tags: ['TypeScript', 'WebSockets', 'Mapbox'],
            link: '#',
            hue: 168,
          },
          {
            title: 'Khattat',
            year: '2024',
            desc: 'A drawing tool that mimics the reed pen and suggests connected letterforms as you write in traditional Arabic scripts.',
            tags: ['Canvas', 'Python', 'ML'],
            link: '#',
            hue: 340,
          },
          {
            title: 'Oasis',
            year: '2024',
            desc: 'A calm mobile app that reminds you to drink water and turns your daily habits into a small oasis growing in front of you.',
            tags: ['Flutter', 'Firebase', 'Lottie'],
            link: '#',
            hue: 130,
          },
          {
            title: 'Maqam',
            year: '2023',
            desc: 'A generative music player that composes melodies in Hijaz, Nahawand and Sikah maqams right inside the browser.',
            tags: ['WebAudio', 'Svelte', 'MIDI'],
            link: '#',
            hue: 275,
          },
        ],
      },
      skills: {
        title: 'Skills',
        kicker: 'Stop three',
        blurb: 'The tools I know well',
        icon: 'bolt',
        color: '#2a9d8f',
        groups: [
          {
            title: 'Front end',
            items: [
              { name: 'JavaScript', level: 95 },
              { name: 'TypeScript', level: 88 },
              { name: 'CSS & SVG', level: 92 },
              { name: 'React', level: 85 },
            ],
          },
          {
            title: '3D graphics',
            items: [
              { name: 'Three.js', level: 90 },
              { name: 'GLSL shaders', level: 78 },
              { name: 'Blender', level: 70 },
              { name: 'WebAudio', level: 75 },
            ],
          },
          {
            title: 'Back end & tools',
            items: [
              { name: 'Node.js', level: 82 },
              { name: 'Python', level: 68 },
              { name: 'Git', level: 90 },
              { name: 'Figma', level: 80 },
            ],
          },
        ],
        levelWord: (v) => (v >= 90 ? 'Expert' : v >= 80 ? 'Advanced' : v >= 65 ? 'Intermediate' : 'Beginner'),
      },
      experience: {
        title: 'Experience',
        kicker: 'Stop four',
        blurb: 'Where I have worked and what I learned',
        icon: 'path',
        color: '#5c6bc0',
        roles: [
          {
            role: 'Senior Interactive Developer',
            company: 'Dunes Studio',
            period: '2023 — Present',
            desc: 'Lead a small team building websites and 3D experiences for regional brands, and set the bar for performance and accessibility.',
          },
          {
            role: 'Front-end Developer',
            company: 'Nibras Tech',
            period: '2020 — 2023',
            desc: 'Built an Arabic-first design system with full bidirectional support and halved the load time of the main app.',
          },
          {
            role: 'Freelance Developer',
            company: 'Independent',
            period: '2018 — 2020',
            desc: 'Delivered more than twenty projects for shops, cultural initiatives and start-ups across the Gulf and the Levant.',
          },
          {
            role: 'Programming Intern',
            company: 'University Innovation Lab',
            period: '2016 — 2018',
            desc: 'My first serious encounter with the web and graphics. I made my first game there and forgot to sleep for weeks.',
          },
        ],
      },
      contact: {
        title: 'Get in touch',
        kicker: 'Final stop',
        blurb: 'I would love to hear your idea',
        icon: 'mail',
        color: '#e76f51',
        message:
          'Have an idea, a project or just a question? Write to me and I will reply within two days. I like projects with a story, and my door is always open to collaboration.',
        emailLabel: 'Email',
        socialsTitle: 'Find me online',
        availability: 'Available for new projects starting next month',
        socials: [
          { name: 'GitHub', handle: '@yourname', url: '#' },
          { name: 'LinkedIn', handle: 'in/yourname', url: '#' },
          { name: 'X', handle: '@yourname', url: '#' },
          { name: 'Instagram', handle: '@yourname', url: '#' },
        ],
      },
    },
  },
};

export default content;
