// Visual flow on mobile: builder → checkout → host → guest (map open) → orders. Screenshots to OUT.
import { chromium } from 'playwright';
const BASE = 'http://localhost:3000', OUT = '/tmp/claude-0';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, reducedMotion: process.env.REDUCED ? 'reduce' : 'no-preference' });
const p = await ctx.newPage();
const errs = []; p.on('pageerror', (e) => errs.push(e.message)); p.on('console', (m) => m.type() === 'error' && errs.push(m.text()));
await p.goto(`${BASE}/create?template=lilac`, { waitUntil: 'networkidle' });
await p.screenshot({ path: `${OUT}/f_builder1.png` });
await p.fill('[name=name1]', 'طارق'); await p.fill('[name=name2]', 'هدى');
await p.fill('[name=venue]', 'قاعة الأفراح'); await p.fill('[name=city]', 'الرياض');
await p.click('text=ملاحظات للضيوف');
await p.fill('[name=notes]', 'جنة الأطفال منازلهم');
await p.click('.segmented label:nth-child(3)');
await p.locator('#s-when').scrollIntoViewIfNeeded();
await p.screenshot({ path: `${OUT}/f_builder2.png` });
await p.fill('[name=contactPhone]', '0500000000');
await p.click('#preview-open'); await p.waitForTimeout(700);
await p.screenshot({ path: `${OUT}/f_sheet.png` });
await p.keyboard.press('Escape'); await p.waitForTimeout(600);
await p.click('.submit');
await p.waitForURL(/checkout/); await p.waitForTimeout(500);
await p.screenshot({ path: `${OUT}/f_checkout.png`, fullPage: true });
await p.click('[data-pay]');
await p.waitForURL(/\/host\//); await p.waitForTimeout(1500);
await p.screenshot({ path: `${OUT}/f_host.png` });
await p.click('.xp.details .xp-head'); await p.waitForTimeout(1200);
await p.screenshot({ path: `${OUT}/f_host_details.png` });
const slug = p.url().match(/host\/(\w+)/)[1];
const g = await ctx.newPage(); g.on('pageerror', (e) => errs.push(e.message));
await g.goto(`${BASE}/i/${slug}?to=${encodeURIComponent('أبو محمد')}`, { waitUntil: 'networkidle' });
await g.click('#open'); await g.waitForTimeout(1300);
await g.locator('#map-pill').scrollIntoViewIfNeeded(); await g.waitForTimeout(300);
await g.screenshot({ path: `${OUT}/f_guest_pill.png` });
await g.click('#map-pill'); await g.waitForTimeout(1600);
await g.screenshot({ path: `${OUT}/f_guest_map.png` });
await g.locator('#rsvp').scrollIntoViewIfNeeded();
await g.screenshot({ path: `${OUT}/f_guest_rsvp.png` });
await g.click('[data-step="1"]'); await g.click('#rsvp-form button[type=submit]'); await g.waitForTimeout(1200);
await p.goto(`${BASE}/orders`, { waitUntil: 'networkidle' }); await p.waitForTimeout(800);
await p.screenshot({ path: `${OUT}/f_orders.png` });
console.log('slug', slug, 'errors', errs);
await b.close();
