// Generates public/css/springs.css: physically simulated springs → CSS linear() easings.
// Same parameters as the Framer Motion reference (stiffness/damping/mass).
import fs from 'node:fs';
import { springEasing } from '../public/js/motion.js';

const SPRINGS = {
  smooth: { stiffness: 200, damping: 22, mass: 1.2 },   // expand / collapse (ExpandDetails)
  snappy: { stiffness: 400, damping: 30, mass: 0.8 },   // shared-element morph (ViewOnMap)
  gentle: { stiffness: 246.7, damping: 31.4, mass: 1 }, // duration .4, bounce 0 — content blur-in
  bouncy: { stiffness: 380, damping: 17, mass: 1 },     // press release, pops
  sheet:  { stiffness: 300, damping: 32, mass: 1 },     // bottom sheet / nav indicator
};
let css = '/* generated by scripts/springs.mjs — do not edit */\n:root {\n';
for (const [k, cfg] of Object.entries(SPRINGS)) {
  const { easing, duration } = springEasing(cfg);
  css += `  --spring-${k}: ${easing};\n  --dur-${k}: ${duration}ms;\n`;
}
fs.writeFileSync(new URL('../public/css/springs.css', import.meta.url), css + '}\n');
console.log(css);
