// Bakes the cel-style sprite sheets: node tools/bake.js [sheet...]
// Serves the repo on a local port, renders tools/bake.html in headless Chromium,
// and writes assets/<sheet>.png + .json plus assets/atlas.js for the game.
const path = require('path');
const fs = require('fs');
const http = require('http');
let chromium;
try {
  ({ chromium } = require('playwright'));
} catch (e) {
  ({ chromium } = require('/opt/node22/lib/node_modules/playwright'));
}
(async () => {
  const root = path.join(__dirname, '..');
  const types = { '.html': 'text/html', '.js': 'text/javascript', '.png': 'image/png', '.json': 'application/json', '.css': 'text/css' };
  const server = http.createServer((req, res) => {
    const file = path.join(root, decodeURIComponent(req.url.split('?')[0]));
    if (!file.startsWith(root) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) {
      res.writeHead(404);
      return res.end();
    }
    res.writeHead(200, { 'Content-Type': types[path.extname(file)] || 'application/octet-stream' });
    fs.createReadStream(file).pipe(res);
  });
  await new Promise((r) => server.listen(0, '127.0.0.1', r));
  const port = server.address().port;
  const out = path.join(root, 'assets');
  fs.mkdirSync(out, { recursive: true });
  const exe = fs.existsSync('/opt/pw-browsers/chromium-1194/chrome-linux/chrome') ? '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' : undefined;
  const browser = await chromium.launch({ executablePath: exe });
  const page = await browser.newPage();
  page.on('pageerror', (e) => console.error('PAGE ERROR', e.message));
  await page.goto('http://127.0.0.1:' + port + '/tools/bake.html');
  await page.waitForFunction(() => window.ready);
  await page.waitForTimeout(800);
  const want = process.argv.slice(2);
  const names = want.length ? want : await page.evaluate(() => Object.keys(G.art.sheets));
  const atlasFile = path.join(out, 'atlas.js');
  const runtime = {};
  if (fs.existsSync(atlasFile)) {
    const txt = fs.readFileSync(atlasFile, 'utf8').replace(/^[^{]*/, '').replace(/;\s*$/, '');
    try { Object.assign(runtime, JSON.parse(txt)); } catch (e) {}
  }
  for (const name of names) {
    const r = await page.evaluate((n) => window.bake(n), name);
    fs.writeFileSync(path.join(out, name + '.png'), Buffer.from(r.png.split(',')[1], 'base64'));
    fs.writeFileSync(path.join(out, name + '.json'), JSON.stringify({ frames: r.frames, animations: r.animations, meta: r.meta }, null, 1));
    runtime[name] = r.runtime;
    console.log(name, r.meta.size.w + 'x' + r.meta.size.h, Object.keys(r.frames).length + ' frames');
  }
  fs.writeFileSync(atlasFile, '// generated by tools/bake.js\nG.ATLAS = ' + JSON.stringify(runtime) + ';\n');
  await browser.close();
  server.close();
})();
